language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - echo 'extension=zmq.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
